[skip ci] New CircleCI config
Ref: https://github.com/greenpeace/planet4-nro-generator/blob/72d660c3d4a0bd0cd14f0d7a1cea19959b3291b4/templates/nro/.circleci/config.yml.tmpl

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,8 +7,8 @@ parameters:
     default: false
 
 docker_auth: &docker_auth
-    username: $DOCKERHUB_USERNAME
-    password: $DOCKERHUB_PASSWORD
+  username: $DOCKERHUB_USERNAME
+  password: $DOCKERHUB_PASSWORD
 
 defaults: &defaults
   docker:
@@ -18,23 +18,59 @@ defaults: &defaults
 
 orbs:
   slack: circleci/slack@3.4.2
-
 job_environments:
-  common_environment: &common_environment
-    APP_HOSTPATH: training
-    CONTAINER_PREFIX: planet4-training
-    WP_DB_NAME_PREFIX: planet4-training_wordpress
-  develop_environment: &develop_environment
-    APP_ENVIRONMENT: development
-    APP_HOSTNAME: www-dev.greenpeace.org
-    CLOUDSQL_INSTANCE: p4-develop-k8s
-    GOOGLE_PROJECT_ID: planet-4-151612
-    GCLOUD_CLUSTER: p4-development
-    HELM_NAMESPACE: develop
-    HELM_RELEASE: planet4-training
-    NEWRELIC_APPNAME: P4 training Development
-    WP_DB_NAME: planet4-training_wordpress_develop
-    WP_STATELESS_BUCKET: planet4-training-stateless-develop
+    common_environment: &common_environment
+      APP_HOSTPATH: training
+      CONTAINER_PREFIX: planet4-training
+      WP_DB_NAME_PREFIX: planet4-training_wordpress
+    develop_environment: &develop_environment
+      APP_ENVIRONMENT: development
+      APP_HOSTNAME: www-dev.greenpeace.org
+      CLOUDSQL_INSTANCE: p4-develop-k8s
+      GOOGLE_PROJECT_ID: planet-4-151612
+      GCLOUD_CLUSTER: p4-development
+      HELM_NAMESPACE: develop
+      HELM_RELEASE: planet4-training
+      NEWRELIC_APPNAME: P4 training Development
+      WP_DB_NAME: planet4-training_wordpress_develop
+      WP_STATELESS_BUCKET: planet4-training-stateless-develop
+
+
+commands:
+  approve_job:
+    description: "Approve an on-hold job."
+    parameters:
+      job_name:
+        type: string
+    steps:
+      - run:
+          name: Unhold job "<< parameters.job_name >>"
+          command: |
+            if [ -f /tmp/workspace/approve_workflow ]; then
+              WORKFLOW_ID=$(cat /tmp/workspace/approve_workflow)
+              url="https://circleci.com/api/v2/workflow/$WORKFLOW_ID/job"
+
+              # Get workflow details
+              workflow=$(curl -s -u "${CIRCLE_TOKEN}": -X GET --header "Content-Type: application/json" "$url")
+              echo $workflow
+              # Get approval job id
+              job_id=$(echo "$workflow" | jq -r '.items[] | select(.name=="<< parameters.job_name >>") | .approval_request_id ')
+              echo $job_id
+
+              if [[ -z $job_id ]]; then
+                echo "Approval ID not found"
+                exit 1
+              fi
+
+              echo "Approving << parameters.job_name >> for workflow $url"
+              echo "Job ID: ${job_id}"
+              curl \
+                --header "Content-Type: application/json" \
+                -u "${CIRCLE_TOKEN}:" \
+                -X POST \
+                "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/approve/${job_id}"
+            fi
+
 job_definitions:
   visualtests_reference_steps: &visualtests_reference_steps
     docker:
@@ -107,10 +143,6 @@ job_definitions:
       - run: make persist
       - run: make build
       - run: make push
-      - run:
-          name: Notify failure
-          when: on_fail
-          command: TYPE="Build" notify-job-failure.sh
       - save_cache:
           key: composer-v5-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
           paths:
@@ -124,7 +156,9 @@ job_definitions:
   test_steps: &test_steps
     working_directory: ~/project
     docker:
-      - image: gcr.io/planet-4-151612/p4-codeception:build-12
+      - image: greenpeaceinternational/p4-codeception:latest
+        auth:
+          <<: *docker_auth
       - name: selenium
         image: selenium/standalone-chrome-debug:3.141.59-oxygen
         auth:
@@ -156,30 +190,33 @@ job_definitions:
         type: boolean
         default: false
     steps:
+      - checkout:
+          path: /home/circleci/checkout
       - attach_workspace:
           at: /tmp/workspace
       - run: activate-gcloud-account.sh
-      - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make deploy
+      - run: make prepare-helm
+      - run: make backup
+      - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make deploy-helm
+      - run: make post-deploy
+      - run:
+          name: Extract workflow from commit message
+          command: |
+            UNHOLD_WORKFLOW_LINE=$(git --git-dir=/home/circleci/checkout/.git log --format=%B -n 1 "$CIRCLE_SHA1" | { grep '^\/unhold ' || true; } )
+            echo "line $UNHOLD_WORKFLOW_LINE"
+            if [[ -n $UNHOLD_WORKFLOW_LINE ]]; then
+              WORKFLOW_ID=${UNHOLD_WORKFLOW_LINE#"/unhold "}
+              echo "$WORKFLOW_ID"
+              echo $WORKFLOW_ID > /tmp/workspace/approve_workflow
+            fi
+      - approve_job:
+          job_name: instance-ready
       - when:
           condition: << parameters.is_prod >>
           steps:
-            - run:
-                name: Initiate finish-staging (approve rollback but it won't really)
-                command: |
-                  url="https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job"
-
-                  # Get workflow details
-                  workflow=$(curl -s -u "${CIRCLE_TOKEN}": -X GET --header "Content-Type: application/json" "$url")
-                  # Get approval job id
-                  job_id=$(echo "$workflow" | jq -r '.items[] | select(.name=="rollback-staging") | .approval_request_id ')
-
-                  echo "Finishing staging."
-                  echo "Job ID: ${job_id}"
-                  curl \
-                    --header "Content-Type: application/json" \
-                    -u "${CIRCLE_TOKEN}:" \
-                    -X POST \
-                    "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/approve/${job_id}"
+            - run: echo $CIRCLE_WORKFLOW_ID > /tmp/workspace/approve_workflow
+            - approve_job:
+                job_name: rollback-staging
       - when:
           condition: << parameters.notify >>
           steps:
@@ -233,15 +270,15 @@ jobs:
       - run:
           name: Configure
           command: |
-            ${HOME}/scripts/activate-gcloud-account.sh
-      - run: /home/circleci/sync_to_test_site.sh
+            activate-gcloud-account.sh
+      - run: sync_to_test_site.sh
 
 workflow_definitions:
   on_develop_commit: &on_develop_commit
     context: org-global
     filters:
       branches:
-        only: develop
+        only: main
 
 workflows:
   develop:
